name = "water"
description = "A multi-lingual, lightweight and responsive theme built on water.css"
license = "GPL 3.0"
homepage = "https://thunix.net/~southerntofu/zola/water"
# The minimum version of Zola required
min_version = "0.10.1"
# An optional live demo URL
demo = "https://thunix.net/~southerntofu/themes/zola/water"

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
# The default color scheme. Can be either light or dark.
# Whichever one you choose, it is overriden if the browser supports it.
color = "dark"
# A list of additional stylesheets to load from the index template
stylesheets = []
# Set the max-width for either "main" or "body". Defaults to "main",
# switch to "body" for default water.css behavior
max_width_for = "main" # Can be either main or body
# Sets the max_width for either main or body, depending on the previous
# setting. 800px is the water.css default
max_width = "800px"

# The theme author info: you!
[author]
name = "southerntofu"
homepage = "https://staticadventures.netlib.re"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
[original]
author =  "kognise"
homepage = "https://kognise.github.io/water.css/"
repo = "https://github.com/kognise/water.css"

[translations.fr]
source = "Source de cette page"
readmore = "Lire la suite"
previousPage = "Page précédente"
nextPage = "Page suivante"
dateFormat = "%d/%m/%Y"
[translations.en]
source = "Source for this page"
readmore = "Read more"
previousPage = "Previous page"
nextPage = "Next page"
dateFormat = "%m/%d/%Y"
