name = "water"
description = "A multi-lingual, lightweight and responsive theme built on water.css"
license = "GPL 3.0"
homepage = "https://thunix.net/~southerntofu/zola/water"
# The minimum version of Zola required
min_version = "0.10.1"
# An optional live demo URL
demo = "https://thunix.net/~southerntofu/themes/zola/water"

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
# The default color scheme. Can be either light or dark.
# Whichever one you choose, it is overriden if the browser supports it.
color = "dark"
# A list of additional stylesheets to load from the index template
stylesheets = []
# Set the max-width for either "main" or "body". Defaults to "main",
# switch to "body" for default water.css behavior
max_width_for = "main" # Can be either main or body
# Sets the max_width for either main or body, depending on the previous
# setting. 800px is the water.css default
max_width = "800px"

# If home_section is empty, homepage is generated from the content of the index
# page content/_index*.md. If you want to display a section's latest articles on
# the homepage, set home_section to the name of this section without _index.md,
# like "blog" for content/blog/. Pagination is defined by this section's 
# pagination settings.
home_section = ""
# Show/hide home section title (only when home_section is set)
home_sectiontitle = true
# Determines whether to show full articles on the homepage. If disabled, it will
# only show summaries (if they are defined in the content), or the date/title.
# (only when home_section is set)
home_fullarticles = true


# The settings below point to a markdown page in content/,
# without the "content/" in the path. Additionally, the page
# will be translated in the current language. Use "disabled"
# to disable this specific part of the theme template.
# Defines the header page
header = ""
# Defines the main menu page
menu = ""

# The theme author info: you!
[author]
name = "southerntofu"
homepage = "https://staticadventures.netlib.re"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
[original]
author =  "kognise"
homepage = "https://kognise.github.io/water.css/"
repo = "https://github.com/kognise/water.css"

[translations.fr]
source = "Source de cette page"
readmore = "Lire la suite"
previousPage = "Page précédente"
nextPage = "Page suivante"
dateFormat = "%d/%m/%Y"
[translations.en]
source = "Source for this page"
readmore = "Read more"
previousPage = "Previous page"
nextPage = "Next page"
dateFormat = "%m/%d/%Y"
