name = "water"
description = "A multi-lingual, lightweight and responsive theme built on water.css"
license = "GPL 3.0"
homepage = "https://thunix.net/~southerntofu/zola/water"
# The minimum version of Zola required
min_version = "0.10.1"
# An optional live demo URL
demo = "https://thunix.net/~southerntofu/themes/zola/water"

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
color = "dark"
stylesheets = []

# The theme author info: you!
[author]
name = "southerntofu"
homepage = "https://staticadventures.netlib.re"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
[original]
author =  "kognise"
homepage = "https://kognise.github.io/water.css/"
repo = "https://github.com/kognise/water.css"
